# Generated by Django 3.2.9 on 2021-11-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='pinterest_poster'),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.ImageField(upload_to='pinterest_poster'),
        ),
    ]
