# Generated by Django 3.2.9 on 2021-11-13 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinterest', '0002_auto_20211113_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='series',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='series',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
